spring:
  profiles:
    active: @activatedSpringProfile@

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

---

spring:
  profiles: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://authorization-dot-wsn-01.appspot.com

---

spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

server:
  port: 8090
